2024-10-21 13:47:03,993 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Serg\PycharmProjects\PythonDeveloper\Module12\tests_12_4.py", line 22, in test_run
    runner = Runner(2)
             ^^^^^^^^^
  File "C:\Users\Serg\PycharmProjects\PythonDeveloper\Module12\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-21 13:47:03,994 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Serg\PycharmProjects\PythonDeveloper\Module12\tests_12_4.py", line 14, in test_walk
    runner = Runner('Вася', -5)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Serg\PycharmProjects\PythonDeveloper\Module12\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
